export { default as BackIcon } from './BackIcon';
export { default as ComentsIcon } from './ComentsIcon';
export { default as ConfigIcon } from './ConfigIcon';
export { default as ContactIcon } from './ContactIcon';
export { default as GridIcon } from './GridIcon';
export { default as LikeIcon } from './LikeIcon';
export { default as PlusIcon } from './PlusIcon';
export { default as RestoreIcon } from './RestoreIcon';
export { default as ShareIcon } from './ShareIcon';
export * from './index';
